### ISSUE TITLE
crontab creation have hardcoded script name

### ISSUE THREAD

**Issue by solbu** [christinloehner/linuxcounter-update-examples#12]
Since beeing a long time counter user, I have become depended upon having the old name for the script file name "**counter-machine-update**". I have never used a crontab, and thought I'd do it now. But the script asumes it's called "**lico-update.sh**", which it does not, nor will it ever be named that way on the systems I manage.

Anyone using the built in crontab auto-creation and have renamed the counter script, will fail to have crontab running the script.

The script should not asume it's always named "lico-update.sh", as on some systems, that will be wrong. It should not hardcode the script filename.

**Comment by christinloehner** [comment]
fixed with next commit
